
import java.awt.event.KeyEvent;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class FrameGenapGanjil extends javax.swing.JFrame {
    
    private void clearTextFieldOnFocus() {
    inputAngka.addFocusListener(new java.awt.event.FocusListener() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            // Menghapus isi text field saat fokus diperoleh
            if (inputAngka.getText().equals("Masukkan Angka")) {
                inputAngka.setText("");  // Hapus teks placeholder
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            // Jika text field kosong, tampilkan placeholder
            if (inputAngka.getText().isEmpty()) {
                inputAngka.setText("Masukkan Angka");
            }
        }
    });
}
    
    private boolean isPrime(int number) {
    if (number <= 1) {
        return false; // Angka 1 atau kurang bukan bilangan prima
    }
    for (int i = 2; i <= Math.sqrt(number); i++) {
        if (number % i == 0) {
            return false; // Jika bisa dibagi dengan angka selain 1 dan dirinya, maka bukan prima
        }
    }
    return true; // Jika tidak ada pembagi, maka bilangan prima
}

    
    private void hanyaAngka(KeyEvent e) {
    char c = e.getKeyChar();
    // Memastikan hanya angka yang bisa dimasukkan
    if (!Character.isDigit(c)) {
        e.consume();  // Membatalkan input jika bukan angka
    }
}
    
private void cekGenapGanjil() {
    try {
        // Ambil angka dari inputAngka
        int angka = Integer.parseInt(inputAngka.getText());
        
        // Menentukan apakah angka genap atau ganjil
        if (angka % 2 == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Angka " + angka + " adalah GENAP");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Angka " + angka + " adalah GANJIL");
        }
        
        // Cek apakah angka tersebut bilangan prima
        if (isPrime(angka)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Angka " + angka + " adalah BILANGAN PRIMA");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Angka " + angka + " BUKAN BILANGAN PRIMA");
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan masukkan angka yang valid!");
    }
}


    /**
     * Creates new form FrameGenapGanjil
     */
    public FrameGenapGanjil() {
        initComponents();
        inputAngka.setText("Masukkan Angka"); // Menambahkan placeholder awal
            clearTextFieldOnFocus();  // Panggil fungsi untuk menghapus teks saat fokus
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelAngka = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        inputAngka = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        labelAngka.setText("Masukan Angka:");
        jPanel1.add(labelAngka, new java.awt.GridBagConstraints());

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(btnHitung, gridBagConstraints);

        inputAngka.setPreferredSize(new java.awt.Dimension(120, 22));
        inputAngka.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputAngkaFocusGained(evt);
            }
        });
        inputAngka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputAngkaKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel1.add(inputAngka, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
    cekGenapGanjil();        // TODO add your handling code here:
    }//GEN-LAST:event_btnHitungActionPerformed

    private void inputAngkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputAngkaKeyTyped
      hanyaAngka(evt);  // Panggil fungsi hanyaAngka untuk memvalidasi input        // TODO add your handling code here:
    }//GEN-LAST:event_inputAngkaKeyTyped

    private void inputAngkaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputAngkaFocusGained
inputAngka.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_inputAngkaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGenapGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGenapGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGenapGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGenapGanjil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGenapGanjil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JTextField inputAngka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAngka;
    // End of variables declaration//GEN-END:variables
}
